language: php
sudo: false

php:
  - 7.1

env:
  - SUITE=unit
  - SUITE=integration

matrix:
  fast_finish: true
  allow_failures:
    - env: SUITE=integration

cache:
  directories:
    - "$HOME/.composer/cache"

install:
  - composer update --prefer-source

before_script:
    - wget https://github.com/infection/infection/releases/download/0.6.0/infection.phar
    - wget https://github.com/infection/infection/releases/download/0.6.0/infection.phar.pubkey
    - chmod +x infection.phar

script:
  - ./vendor/bin/phpunit --testsuite $SUITE
  - ./infection.phar --min-msi=50 --min-covered-msi=80
